### ISSUE TITLE
Add a summary overall visual's image to README.md

### ISSUE THREAD

**Issue by hugolpz** [nushu-script/font-unicode-nushu#1]
Hello,

It may be interesting to visualize your font in the read me. Something like this [Wikipedia table](https://en.wikipedia.org/wiki/N%C3%BCshu#In_Unicode) (but with higher px quality):

![Screenshot_2020-10-04_23-24-32](https://user-images.githubusercontent.com/1420189/95027449-cda6fa00-0698-11eb-9185-4f0d7a163d5d.png)

(I suspect your font is the one used within https://unicode.org/charts/PDF/U1B170.pdf but I'am not sure)

Also, just thank you for this project. So encouraging to see people support linguistic diversity :speech_balloon: :heart:

**Comment by sgalal** [comment]
Hi, @hugolpz. I have added the summary overall visual’s image.

Besides, please be aware of copyright issues when using the font. I have translated the related paragraphs in the README to English.

By the way, since the strokes of this font are relatively thin, it is not suitable to be used in the browser for now. If you want to display Nushu on websites, please checkout [Noto Traditional Nushu](https://github.com/notofonts/NotoTraditionalNushu) and [Noto Sans Nüshu](https://github.com/notofonts/noto-sans-nushu). The web fonts are available in the [nushu-script](https://github.com/nushu-script) organization.
